### ISSUE TITLE
Bug: choosing specific sorting option prevent images from loading

### ISSUE THREAD

**Issue by Nixonpolska** [cocktailpeanut/breadboard#10]
https://user-images.githubusercontent.com/121901372/210445191-b22db4b1-60a5-4524-a7dc-9dd79dc2285c.mp4

As you can see on the video. Same thing happens also when there isn't any input inside textbox.

**Comment by cocktailpeanut** [comment]
This should be fixed now. Please reopen if you still experience this problem. Closing.
