### ISSUE TITLE
Search syntax to pick up aesthetic score tags?

### ISSUE THREAD

**Issue by Mousewrites** [cocktailpeanut/breadboard#27]
Hey there! Loving breadboard, it's almost exactly what I need.

However, i'm running into a snag. I have a lot if images that have aesthetic scores written into the prompt, like this:

![image](https://user-images.githubusercontent.com/114956889/212233540-375b775f-6715-45af-a2be-7ea2feb4372f.png)

But they show up as separate tags, and so I can't actually use them to sort by score. 
![image](https://user-images.githubusercontent.com/114956889/212233639-7388eaec-315c-4914-9cef-35c681093939.png)

I've tried searching by 

- aesthetic_score: 6.6 - returns nothing
- aesthetic score 6 6 - returns every image that has aesthetic, score, or the number 6
- "aesthetic score 6 6" - returns nothing

I suspect there's a way to tell it to give me exactly the string "aesthetic score 6 6", but I can't find it. Help?

**Comment by cocktailpeanut** [comment]
@Mousewrites can you share a file so I can try on my end and debug?

When you upload, make sure to zip it first (otherwise github will strip out the metadata).

**Comment by Mousewrites** [comment]
[00068-3777209250.zip](https://github.com/cocktailpeanut/breadboard/files/10408109/00068-3777209250.zip)

**Comment by cocktailpeanut** [comment]
Today released 0.4.3 that implements another aesthetic scorer extension https://www.reddit.com/r/StableDiffusion/comments/1193dru/releasing_breadboard_043_browse_filter_and/

Now probably supports all aesthetic score variations (when it comes to auto1111). Closing.

Please reopen if you find an issue
