### ISSUE TITLE
Windows scrollbar handle can hide behind the min/max/close buttons

### ISSUE THREAD

**Issue by StrawberryBunny** [cocktailpeanut/breadboard#38]
On Windows when the scrollbar handle is all the way at the top it hides behind the system buttons.
If you have scrolled down and loaded in enough images that the scrollbar handle is quite small, it can entirely disappear from view. 
This may cause some accessibility issues for those that need to use their mouse cursor to click and drag the bar instead of using a scroll wheel. 

The scrollbar handle just peeking out from under the buttons:
![2023-01-26 16_36_19-breadboard](https://user-images.githubusercontent.com/19222668/214899360-d081c484-8370-4c9c-8939-f41f208e4d9b.png)

Scrolled down a little bit so you can see the actual size of the scrollbar handle.
![2023-01-26 16_36_03-breadboard](https://user-images.githubusercontent.com/19222668/214899376-4e059c4f-2a63-410e-a581-d94d54db34da.png)

**Comment by cocktailpeanut** [comment]
Think this should be fixed with 0.4.0 https://www.reddit.com/r/StableDiffusion/comments/111dc2l/breadboard_040_realtime_messenger_for_stable/

Please feel free to close the issue if it's been fixed. Otherwise let me know.

**Comment by StrawberryBunny** [comment]
It is. Nice work.
