### ISSUE TITLE
Dark mode where

### ISSUE THREAD

**Issue by reaper9037** [cocktailpeanut/breadboard#6]
Great app, but not a fan of getting flashbanged every time i take a look at it

**Comment by cocktailpeanut** [comment]
Darkmode added https://breadboard.me/docs/#/?id=theme

To learn more, check out the announcement: https://www.reddit.com/r/StableDiffusion/comments/102ca1u/breadboard_a_stablediffusion_browser_version_010/

and the full release note here: https://github.com/cocktailpeanut/breadboard/releases/tag/0.1.0

Thanks for the feedback!
